const EftiWall = {
  "0": "              \n     ...      \n    (. .)     \nooO--(_)--Ooo-",
  "1": "              \n     ...      \n    (o o)     \nooO--(_)--Ooo-",
  "2": "              \n     ...      \n    (- o)     \nooO--(_)--Ooo-",
  "3": "              \n     ...      \n    (o -)     \nooO--(_)--Ooo-",
  "4": "              \n     ...      \n    (- -)     \nooO--(_)--Ooo-",
  "5": "              \n     ...      \n    (* *)     \nooO--(_)--Ooo-",
  "6": "              \n     ...      \n    (x x)     \nooO--(_)--Ooo-",
  "7": "              \n     ...      \n    (o O)     \nooO--(_)--Ooo-",
  "8": "              \n     ...      \n    (O o)     \nooO--(_)--Ooo-",
  "9": "              \n     ...      \n    ( oo)     \nooO--(_)--Ooo-",
  "A": "              \n     ___      \n    (o o)     \nooO--(_)--Ooo-",
  "B": "              \n     ,,,      \n    (o o)     \nooO--(_)--Ooo-",
  "C": "              \n     ooo      \n    (o o)     \nooO--(_)--Ooo-",
  "D": "              \n     ===      \n    (o o)     \nooO--(_)--Ooo-",
  "E": "              \n     +++      \n    (o o)     \nooO--(_)--Ooo-",
  "F": "              \n     ###      \n    (o o)     \nooO--(_)--Ooo-",
  "G": "              \n    -*~*-     \n    (o o)     \nooO--(_)--Ooo-",
  "H": "              \n     ***      \n    (o o)     \nooO--(_)--Ooo-",
  "I": "              \n     |||      \n    (o o)     \nooO--(_)--Ooo-",
  "J": "              \n    -`^'-     \n    (o o)     \nooO--(_)--Ooo-",
  "K": "              \n     /777     \n    (o o)     \nooO--(_)--Ooo-",
  "L": "              \n     _/7      \n    (o o)     \nooO--(_)--Ooo-",
  "M": "              \n     )))      \n    (o o)     \nooO--(_)--Ooo-",
  "N": "              \n     (((      \n    (o o)     \nooO--(_)--Ooo-",
  "O": "              \n     xxx      \n    (o o)     \nooO--(_)--Ooo-",
  "P": "              \n  `  ___  '   \n -  (O o)  -  \nooO--(_)--Ooo-",
  "Q": "              \n     @__      \n    (o o)     \nooO--(_)--Ooo-",
  "R": "      _       \n     ((_      \n    (o o)     \nooO--(_)--Ooo-",
  "S": "              \n     >X<      \n    (o o)     \nooO--(_)--Ooo-",
  "T": "              \n     '*`      \n    (o o)     \nooO--(_)--Ooo-",
  "U": "              \n    \\-^-/     \n    (o o)     \nooO--(_)--Ooo-",
  "V": "              \n     ^^^      \n    (o o)     \nooO--(_)--Ooo-",
  "W": "              \n     )|(      \n    (o o)     \nooO--(_)--Ooo-",
  "X": "              \n     \\|/      \n    (o o)     \nooO--(_)--Ooo-",
  "Y": "              \n     &&&      \n    (o o)     \nooO--(_)--Ooo-",
  "Z": "     (        \n     _)_      \n    (o o)     \nooO--(_)--Ooo-"
}

export default EftiWall